site_name: Jiaqi Guo
site_dir: target
logo: images/noodle_logo_48.png
theme:
  name: readthedocs
  custom_dir: theme
markdown_extensions:
  - tables
  - fenced_code
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html
extra_css:
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.1.0/dist/cookieconsent.css
  - css/page_layout.css
  - css/markdown_styles.css
extra_javascript:
  - https://code.jquery.com/jquery-3.7.1.min.js
  - js/main.js
  - https://cdn.jsdelivr.net/gh/orestbida/cookieconsent@3.1.0/dist/cookieconsent.umd.js
  - js/cookieconsent_config.js
