name: maven_publish

on:
  workflow_call:
    inputs:
      cmd:
        type: string
        required: false
        default: "mvn -B --update-snapshots verify package javadoc:javadoc site"
        description: "The full mvn command to run to generate artifacts."
      publish_site:
        type: boolean
        required: false
        default: true
        description: "Publsih maven generated site to Github page."

jobs:
  publish:
    permissions:
      contents: read
      pages: write
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Use Java
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'zulu'
        cache: maven
    - run: ${{ inputs.cmd }}
    - name: Deploy artifact
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload site
      if: ${{ inputs.publish_site }}
      uses: actions/upload-pages-artifact@v4
      with:
        path: target/site
    - name: Deploy site
      if: ${{ inputs.publish_site }}
      uses: actions/deploy-pages@v4
