name: maven_verify

on:
  workflow_call:
    inputs:
      cmd:
        type: string
        required: false
        default: "mvn -B --update-snapshots javadoc:javadoc verify site"
        description: "The full mvn command to run."

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Run Maven
        run: ${{ inputs.cmd }}

