name: publish

on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  publish:
    uses: ./.github/workflows/maven-publish.yml
    with:
        cmd: mvn -B verify package
        publish_site: false
