name: publish_www

on:
  push:
    branches:
      - main
    paths:
      - "www"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: python -m mkdocs build -f www/mkdocs.yml
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: www/target
      - uses: actions/deploy-pages@v5
        