name: verify

on:
  push:
    paths-ignore:
      - "**/*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  verify:
    uses: ./.github/workflows/maven-verify.yml
    with:
        cmd: mvn -B verify
